version: "2"
services:
  api:
    container_name: restful_api_server
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://db:27017/restful_api
      - AUTHORIZATION_TOKEN=5CD4ED173E1C95FE763B753A297D5
    ports:
      - "3000:3000"
    links:
      - "db"
  db:
    container_name: restful_api_database
    image: mongo:3.6
    ports:
      - "27017:27017"
